baseURL = "https://theblackstonecenter.github.io/"
title = "The Blackstone Center"
author = "The William E. Blackstone Center"
description = "A center dedicated to exploring the human experience through literature and community engagement."
